default: true
MD013: false   # line length
MD033: false   # inline HTML allowed
MD041: false   # first line heading not required

#allow empty links:
MD042: false

#empty spaces 0-2
MD009: false

# Allow 3 spaces after list markers
MD030:
  ul_single: 3
  ol_single: 1

# Allow 3-space indentation for nested unordered lists
MD007:
  indent: 3

# (Optional) Ignore trailing spaces; or remove this to enforce trimming
MD009: false
